apiVersion: v2
name: crossplane
description: A Helm chart for deploying and configuring crossplane

type: application
version: "1.0.0"
appVersion: "1.17.0"

dependencies:
  - name: crossplane
    version: 1.17.1
    repository: https://charts.crossplane.io/stable/
