apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes

type: application
version: 0.5.0
appVersion: "1.16.0"

dependencies:
  - name: cert-manager
    version: "v1.16.1"
    repository: https://charts.jetstack.io