apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL:  https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.1
    helm:
      releaseName: nginx-ingress-controller
      parameters:
        - name: 'controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"'
          value: "nlb"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-controller
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
---
apiVersion: route53.aws.upbound.io/v1beta1
kind: Record
metadata:
  name: fhochleitner.dev
spec:
  forProvider:
    name: fhochleitner.dev
    alias:
    - evaluateTargetHealth: true
      name: a67b53e0ed5044e9cb880378307cbacc-9242b36b7fa2574a.elb.eu-west-1.amazonaws.com
      zoneId: Z2IFOLAFXWLO4F
    region: eu-west-1
    type: A
    zoneId: Z051402718Y86EFGK6LD4
---
apiVersion: route53.aws.upbound.io/v1beta1
kind: Record
metadata:
  name: fhochleitner.dev
spec:
  forProvider:
    name: fhochleitner.dev
    alias:
      - evaluateTargetHealth: true
        name: a67b53e0ed5044e9cb880378307cbacc-9242b36b7fa2574a.elb.eu-west-1.amazonaws.com
        zoneId: blubb
    region: eu-west-1
    type: A
    zoneId: blubb