apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-cluster-network
  annotations:
    meta.crossplane.io/version: 0.0.3
    meta.crossplane.io/description: |
      A crossplane configuration for deploying a workload cluster network on AWS.
spec:
  crossplane:
    version: ">=v1.16.0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      # renovate: datasource=github-releases depName=upbound/provider-aws
      version: ">=v1.14.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      # renovate: datasource=github-releases depName=crossplane-contrib/function-auto-ready
      version: ">=v0.2.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      # renovate: datasource=github-releases depName=crossplane-contrib/function-go-templating
      version: ">=v0.5.0"
